default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
  port: <%= ENV.fetch("POSTGRES_PORT", "5432") %>
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "password") %>
  database: <%= ENV.fetch("POSTGRES_DB", "rails7-docker-app") %>

development:
  <<: *default

test:
  <<: *default
  database: rails7-docker-app-test

staging:
  <<: *default

production:
  <<: *default