# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "develop" ]
  workflow_call:
jobs:
  rspec:
    runs-on: ubuntu-20.04
    env:
      RAILS_ENV: test
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: localhost

    services:
      postgres:
        image: postgres:14-alpine
        ports:
          - 5432:5432
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true
      - name: Set up PostgreSQL
        run: |
          sudo systemctl start postgresql
          sudo -u postgres psql -c "ALTER USER postgres PASSWORD 'password';"
      - name: Run tests
        run: |
          bundle exec rake db:create db:migrate RAILS_ENV=test
          bundle exec rspec

  rubocop:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true
      - name: rubocop
        run: bundle exec rubocop

  rails_best_practices:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true
      - name: rails_best_practices
        run: bundle exec rails_best_practices